travis:
  secure:
    BINSTAR_TOKEN: GNIKkmMMJkFMmaq+pqPvnCgABnn/bIvrHUA1N+qpdh33G1M6sLKQZ+LA6w93/qHzU3EajXlTJyyCNLFej5VZ6Tfh9LAk2r2L9dEzBZxlW3Z70l/umxWXFOadjh3UqhEVjJnaIsIrd98QeRZ2e3AssrSi3V4EcfqQFvBi363uXAYBegYzYk7Zs/3Kr+4iXqc6DRICYm5QI5hueSKEHvzQAHtKPRhN0cMuxiyngFc006mbqguQFNOhNsHyVT9zMIb9FtpNRP87pjRzpHXpj2qvE93oJB3qMTVu3fAY7ntqrb0kzVZF7WzEKNNRSeVOeGFI1Jrtj/7iblIe0UZI0s7aIK+SPDfuQTofUFikvDXCipvDzHd54v4UQUR05sD6MdCbYlewxQFmmdS8uEqNVKvSHemB+fOfeM97kmr8assZPNIp8Nc3VxBLOsC7MVuc1mliFRGezxqUQJpNRMtO5+PotfgDZ6GALU8HP3i4nJ6hPMmKKMefytbNWlF7dv677kyDEgmcQPjK1hO+OCaty2g2iV5aTpmkf/ydj4reOhHi0pJkLIoKxPE38JjnYEOX6+SXFOBbFoo6gQP8S7Gz5qqTvyeTUUvgOFXqLKDhsiJG/T35H8kFuhlKfnkL50ERzOb6pSEDeU5AEqFpk6NOzaHCsitQZm7QiaEMgOF2GhHhwXs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
